[formatting]
align_entries         = true
reorder_arrays        = true
reorder_keys          = false
reorder_inline_tables = false

[[rule]]
include = ["**/Cargo.toml"]
keys    = ["dependencies"]

[rule.formatting]
reorder_keys = true
